# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Build stage
FROM node:lts-alpine AS build
WORKDIR /app

# Copy dependency manifests and TypeScript config
COPY package.json package-lock.json tsconfig.json ./

# Copy TypeScript source files and public assets
COPY *.ts ./
COPY public ./public

# Install dependencies and build
RUN npm install
RUN npm run build

# Runtime stage
FROM node:lts-alpine AS runtime
WORKDIR /app

# Copy built artifacts and production modules
COPY --from=build /app/build ./build
COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/public ./public

# --- START SECURITY FIX ---
# 1. Create a dedicated group and user with no privileges
RUN addgroup --system appgroup && adduser --system --ingroup appgroup appuser

# 2. Change the ownership of the application files to the new user
RUN chown -R appuser:appgroup /app

# 3. Switch to the non-root user
USER appuser
# --- END SECURITY FIX ---

# Expose port for Spotify auth callback
EXPOSE 8080

# Default command to start the MCP server
CMD ["node", "build/index.js"]
